# Generated by Django 5.1.1 on 2025-02-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='courts',
        ),
        migrations.AddField(
            model_name='club',
            name='courts_summary',
            field=models.JSONField(default=list, help_text="Store a summary of courts, e.g., [{'type': 'hard', 'count': 3}]"),
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_type', models.CharField(choices=[('hard', 'Hard'), ('clay', 'Clay'), ('grass', 'Grass')], max_length=20)),
                ('court_number', models.IntegerField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_details', to='api.club')),
            ],
        ),
    ]
