# Generated by Django 5.1.1 on 2025-03-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_club_closing_time_club_opening_time_court_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='booking_increment',
            field=models.IntegerField(default=30, help_text='Booking time increment in minutes'),
        ),
        migrations.AddField(
            model_name='club',
            name='max_advance_booking_days',
            field=models.IntegerField(default=14, help_text='Maximum days in advance for booking'),
        ),
        migrations.AddField(
            model_name='club',
            name='max_booking_duration',
            field=models.IntegerField(default=120, help_text='Maximum booking duration in minutes'),
        ),
        migrations.AddField(
            model_name='club',
            name='min_booking_duration',
            field=models.IntegerField(default=60, help_text='Minimum booking duration in minutes'),
        ),
        migrations.AddField(
            model_name='club',
            name='same_day_booking_cutoff',
            field=models.IntegerField(default=0, help_text='Hours before start time that same-day booking is cut off'),
        ),
        migrations.CreateModel(
            name='CourtAvailabilityRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_restrictions', to='api.court')),
            ],
            options={
                'verbose_name': 'Court restriction',
                'verbose_name_plural': 'Court restrictions',
            },
        ),
        migrations.CreateModel(
            name='ClubSpecialHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_hours', to='api.club')),
            ],
            options={
                'verbose_name': 'Special hours',
                'verbose_name_plural': 'Special hours',
                'unique_together': {('club', 'date')},
            },
        ),
    ]
